Update open-slack-channel.yaml

diff --git a/.github/workflows/open-slack-channel.yaml b/.github/workflows/open-slack-channel.yaml
--- a/.github/workflows/open-slack-channel.yaml
+++ b/.github/workflows/open-slack-channel.yaml
@@ -123,82 +123,94 @@ jobs:
       #         exit 1 
       #       fi
       #     done
-      
+
       - name: Add Members to Slack Channel
         id: add_members
         if: success()
         env:
           SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
-          CHANNEL_ID: C06QYNQQZU3
-          clientId: ${{ secrets.PORT_CLIENT_ID }}
-          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
-        run: |
-          # Step 1: Get the Port access token
-          PORT_TOKEN_RESPONSE=$(curl -s -X 'POST' \
-          curl -X 'POST' \
-            'https://api.getport.io/v1/auth/access_token' \
-            -H 'accept: application/json' \
-            -H 'Content-Type: application/json' \
-            -d "{
-                  \"clientId\": \"$clientId\",
-                  \"clientSecret\": \"$clientSecret\"
-                }"
-              )
+          CHANNEL_ID: 'C06QYNQQZU3'
+          CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
+          CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
+          RUN_ID: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
+          MEMBER_EMAILS: ${{ toJSON(github.event.inputs.members) }}
+        run: bash ./src/add_members_to_slack.sh "$SLACK_TOKEN" "$CHANNEL_ID" "$CLIENT_ID" "$CLIENT_SECRET" "$RUN_ID" "$MEMBER_EMAILS"
 
-          echo $PORT_TOKEN_RESPONSE
-          PORT_ACCESS_TOKEN=$(echo $PORT_TOKEN_RESPONSE | jq -r '.accessToken')
+      # - name: Add Members to Slack Channel
+      #   id: add_members
+      #   if: success()
+      #   env:
+      #     SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
+      #     CHANNEL_ID: C06QYNQQZU3
+      #     clientId: ${{ secrets.PORT_CLIENT_ID }}
+      #     clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
+      #   run: |
+      #     # Step 1: Get the Port access token
+      #     PORT_TOKEN_RESPONSE=$(curl -s -X 'POST' \
+      #     curl -X 'POST' \
+      #       'https://api.getport.io/v1/auth/access_token' \
+      #       -H 'accept: application/json' \
+      #       -H 'Content-Type: application/json' \
+      #       -d "{
+      #             \"clientId\": \"$clientId\",
+      #             \"clientSecret\": \"$clientSecret\"
+      #           }"
+      #         )
+
+      #     echo $PORT_TOKEN_RESPONSE
+      #     PORT_ACCESS_TOKEN=$(echo $PORT_TOKEN_RESPONSE | jq -r '.accessToken')
       
-          # Ensure the access token was obtained successfully
-          if [ -z "$PORT_ACCESS_TOKEN" ] || [ "$PORT_ACCESS_TOKEN" == "null" ]; then
-            error_message="Failed to obtain Port access token ❌"
-            echo $error_message
-            report_error "$error_message"
-            exit 1
-          fi
+      #     # Ensure the access token was obtained successfully
+      #     if [ -z "$PORT_ACCESS_TOKEN" ] || [ "$PORT_ACCESS_TOKEN" == "null" ]; then
+      #       error_message="Failed to obtain Port access token ❌"
+      #       echo $error_message
+      #       report_error "$error_message"
+      #       exit 1
+      #     fi
       
-          # Step 2: The rest of your script
-          run_id=${{ fromJson(github.event.inputs.port_payload).context.runId }}
-          user_ids=""
-          MEMBER_EMAILS=${{ toJSON(github.event.inputs.members) }}
+      #     # Step 2: The rest of your script
+      #     run_id=${{ fromJson(github.event.inputs.port_payload).context.runId }}
+      #     user_ids=""
+      #     MEMBER_EMAILS=${{ toJSON(github.event.inputs.members) }}
       
-          function report_error {
-            local message=$1
-            echo $message
-            echo "ADD_MEMBER_TO_CHANNEL_ERROR=$message" >> $GITHUB_ENV
-            curl -s -X POST "https://api.getport.io/v1/actions/runs/$run_id/logs" \
-              -H "Content-Type: application/json" \
-              -H "Authorization: Bearer $PORT_ACCESS_TOKEN" \
-              -d "{\"message\": \"$message\"}"
-          }
+      #     function report_error {
+      #       local message=$1
+      #       echo $message
+      #       echo "ADD_MEMBER_TO_CHANNEL_ERROR=$message" >> $GITHUB_ENV
+      #       curl -s -X POST "https://api.getport.io/v1/actions/runs/$run_id/logs" \
+      #         -H "Content-Type: application/json" \
+      #         -H "Authorization: Bearer $PORT_ACCESS_TOKEN" \
+      #         -d "{\"message\": \"$message\"}"
+      #     }
       
-          for email in $(echo $MEMBER_EMAILS | jq -r '.[]'); do
-            user_response=$(curl -s -X GET "https://slack.com/api/users.lookupByEmail?email=$email" \
-              -H "Authorization: Bearer $SLACK_TOKEN")
+      #     for email in $(echo $MEMBER_EMAILS | jq -r '.[]'); do
+      #       user_response=$(curl -s -X GET "https://slack.com/api/users.lookupByEmail?email=$email" \
+      #         -H "Authorization: Bearer $SLACK_TOKEN")
       
-            if [[ "$(echo $user_response | jq -r '.ok')" == "true" ]]; then
-              user_id=$(echo $user_response | jq -r '.user.id')
-              user_ids+="${user_id},"
-            else
-              error_message="Failed to retrieve user id for $email: $(echo $user_response | jq -r '.error' | tr '_' ' ') ⚠️"
-              report_error "$error_message"
-            fi
-          done
+      #       if [[ "$(echo $user_response | jq -r '.ok')" == "true" ]]; then
+      #         user_id=$(echo $user_response | jq -r '.user.id')
+      #         user_ids+="${user_id},"
+      #       else
+      #         error_message="Failed to retrieve user id for $email: $(echo $user_response | jq -r '.error' | tr '_' ' ') ⚠️"
+      #         report_error "$error_message"
+      #       fi
+      #     done
       
-          user_ids=${user_ids%,}
+      #     user_ids=${user_ids%,}
       
-          if [[ -n "$user_ids" ]]; then
-            invite_response=$(curl -s -X POST "https://slack.com/api/conversations.invite" \
-              -H "Content-Type: application/json" \
-              -H "Authorization: Bearer $SLACK_TOKEN" \
-              --data "{\"channel\":\"$CHANNEL_ID\",\"users\":\"$user_ids\"}")
+      #     if [[ -n "$user_ids" ]]; then
+      #       invite_response=$(curl -s -X POST "https://slack.com/api/conversations.invite" \
+      #         -H "Content-Type: application/json" \
+      #         -H "Authorization: Bearer $SLACK_TOKEN" \
+      #         --data "{\"channel\":\"$CHANNEL_ID\",\"users\":\"$user_ids\"}")
       
-            if [[ "$(echo $invite_response | jq -r '.ok')" == "false" ]]; then
-              error_message="Failed to invite users to channel: $(echo $invite_response | jq -r '.error' | tr '_' ' ') ⚠️"
-              report_error "$error_message"
-            fi
-          else
-            report_error "No user IDs found to invite."
-          fi
+      #       if [[ "$(echo $invite_response | jq -r '.ok')" == "false" ]]; then
+      #         error_message="Failed to invite users to channel: $(echo $invite_response | jq -r '.error' | tr '_' ' ') ⚠️"
+      #         report_error "$error_message"
+      #       fi
+      #     else
+      #       report_error "No user IDs found to invite."
+      #     fi
 
       - name: Log If Request to Add Members is Successful
         uses: port-labs/port-github-action@v1
