Update open-slack-channel.yaml

diff --git a/.github/workflows/open-slack-channel.yaml b/.github/workflows/open-slack-channel.yaml
--- a/.github/workflows/open-slack-channel.yaml
+++ b/.github/workflows/open-slack-channel.yaml
@@ -39,18 +39,42 @@ jobs:
           runId: ${{fromJson(github.event.inputs.port_payload).context.runId}}
           logMessage: "About to create a conversation channel in slack..."
 
+      # - name: Create Slack Channel
+      #   id: create_channel
+      #   uses: fjogeleit/http-request-action@v1
+      #   with:
+      #     url: 'https://slack.com/api/conversations.create'
+      #     method: 'POST'
+      #     customHeaders: '{ "Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.BOT_USER_OAUTH_TOKEN }}" }'
+      #     data: >-
+      #         '{
+      #           "name": ${{inputs.channel_name}},
+      #           "is_private": ${{inputs.is_private}}
+      #         }'
+
       - name: Create Slack Channel
         id: create_channel
-        uses: fjogeleit/http-request-action@v1
-        with:
-          url: 'https://slack.com/api/conversations.create'
-          method: 'POST'
-          customHeaders: '{ "Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.BOT_USER_OAUTH_TOKEN }}" }'
-          data: >-
-              '{
-                "name": ${{inputs.channel_name}},
-                "is_private": ${{inputs.is_private}}
-              }'
+        env:
+          SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
+        run: |
+          response=$(curl -s -X POST "https://slack.com/api/conversations.create" \
+            -H "Authorization: Bearer $SLACK_TOKEN" \
+            -H "Content-Type: application/json" \
+            --data "{\"name\": \"${{ github.event.inputs.channel }}\",\"is_private\": ${{ github.event.inputs.is_private }} }")
+  
+          # Extract the channel ID
+          channel_id=$(echo $response | jq -r '.channel.id')
+          echo "Channel ID: $channel_id"
+          
+          if [ "$channel_id" != "null" ]; then
+            # Use GITHUB_ENV to set the channel_id environment variable for subsequent steps
+            echo "CHANNEL_ID=$channel_id" >> $GITHUB_ENV
+          else
+            echo "Failed to create Slack channel"
+            echo "Response: $response"
+            exit 1
+          fi
+
               
       - name: Log If Request Fails 
         if: failure()
